# docker login --username=lai****@live.com registry.cn-shanghai.aliyuncs.com
# docker push registry.cn-shanghai.aliyuncs.com/laizhan/jinbaole
# docker-compose up -d
# docker-compose ps
# docker-compose down


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.cn-shanghai.aliyuncs.com/laizhan/jinbaole
    container_name: jinbaole
    ports:
      - "8080:80"
    restart: unless-stopped

networks:
  default:
    driver: bridge